name: Airflow Issue Alert

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # 每 5 分鐘執行一次
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install requests python-dotenv
      - name: Run bot
        run: python github_monitor.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}